# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import urllib.request
from PIL import Image

class TestA():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_a(self):
    # Test name: a
    # Step # | name | target | value
    # 1 | open | https://www.imdb.com/chart/top/?ref_=nv_mv_250 | 
    self.driver.get("https://www.imdb.com/chart/top/?ref_=nv_mv_250")
    # 2 | setWindowSize | 1054x800 | 
    self.driver.set_window_size(1054, 800)
    # 3 | click | linkText=Esaretin Bedeli | 
    self.driver.find_element(By.LINK_TEXT, "Esaretin Bedeli").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")

    a= self.driver.find_element(By.CLASS_NAME, "ipc-image").get_attribute("src")
    urllib.request.urlretrieve(a,"esaret.jpg")
    img=Image.open("esaret.jpg")
    img.show()    
    # 5 | close |  | 
    self.driver.close()
  
run = TestA()
run.setup_method()
run.test_a()